#!/usr/bin/env python3
"""Prepare private per-user configuration for a local Spaghetti Desk install."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

APP_DIRECTORY_NAME = "spaghetti-desk"
CONFIG_FILE_NAME = "config.yaml"
COMPOSE_ENV_FILE_NAME = "compose.env"
COMPOSE_OVERRIDE_FILE_NAME = "docker-compose.user.yml"


def default_config_directory() -> Path:
    """Return the platform-appropriate per-user configuration directory."""
    xdg_config_home = os.getenv("XDG_CONFIG_HOME")
    if xdg_config_home:
        return Path(xdg_config_home).expanduser() / APP_DIRECTORY_NAME

    app_data = os.getenv("APPDATA")
    if os.name == "nt" and app_data:
        return Path(app_data).expanduser() / "SpaghettiDesk"

    return Path.home() / ".config" / APP_DIRECTORY_NAME


def _secure_permissions(path: Path, mode: int) -> None:
    if os.name != "nt":
        path.chmod(mode)


def _create_config(template: Path, destination: Path) -> bool:
    try:
        with destination.open("x", encoding="utf-8") as config_file:
            config_file.write(template.read_text(encoding="utf-8"))
    except FileExistsError:
        return False

    _secure_permissions(destination, 0o600)
    return True


def _write_compose_environment(path: Path) -> None:
    header = [
        "# Managed by scripts/install-local.py.",
        "# Keep credentials private and never commit this file.",
    ]
    if path.exists():
        updated_lines = path.read_text(encoding="utf-8").splitlines()
    else:
        updated_lines = [*header, "", "JENKINS_USERNAME=", "JENKINS_TOKEN="]

    path.write_text("\n".join(updated_lines) + "\n", encoding="utf-8")
    _secure_permissions(path, 0o600)


def _write_compose_override(path: Path, config_directory: Path) -> None:
    source = json.dumps(config_directory.resolve().as_posix())
    content = f"""# Generated by scripts/install-local.py. Re-run the installer to refresh it.
services:
  backend:
    environment:
      SPAGHETTI_CONFIG_PATH: /app/user-config/config.yaml
      SPAGHETTI_COMPOSE_ENV_PATH: /app/user-config/compose.env
      SPAGHETTI_CONFIG_WRITABLE: \"true\"
    volumes:
      - type: bind
        source: {source}
        target: /app/user-config
"""
    path.write_text(content, encoding="utf-8")
    _secure_permissions(path, 0o600)


def install(config_directory: Path, template: Path) -> tuple[Path, Path, Path, bool]:
    config_directory.mkdir(parents=True, exist_ok=True)
    _secure_permissions(config_directory, 0o700)

    config_path = config_directory / CONFIG_FILE_NAME
    created = _create_config(template, config_path)
    _secure_permissions(config_path, 0o600)

    compose_env_path = config_directory / COMPOSE_ENV_FILE_NAME
    _write_compose_environment(compose_env_path)
    compose_override_path = config_directory / COMPOSE_OVERRIDE_FILE_NAME
    _write_compose_override(compose_override_path, config_directory)
    return config_path, compose_env_path, compose_override_path, created


def _parse_args() -> argparse.Namespace:
    project_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(
        description="Create private user configuration and Docker path settings."
    )
    parser.add_argument(
        "--config-dir",
        type=Path,
        default=default_config_directory(),
        help="override the platform user configuration directory",
    )
    parser.add_argument(
        "--template",
        type=Path,
        default=project_root / "config" / "private.example.yaml",
        help=argparse.SUPPRESS,
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    if not args.template.is_file():
        raise SystemExit(f"configuration template not found: {args.template}")

    config_path, compose_env_path, compose_override_path, created = install(
        args.config_dir.expanduser(), args.template
    )
    state = "created" if created else "kept existing"
    print(f"Configuration: {config_path} ({state})")
    print(f"Docker environment: {compose_env_path}")
    print(f"Docker override: {compose_override_path}")
    print("Start Spaghetti Desk with:")
    compose_env_argument = json.dumps(compose_env_path.as_posix())
    compose_override_argument = json.dumps(compose_override_path.as_posix())
    print(
        "  docker compose "
        f"--env-file {compose_env_argument} "
        "--file docker-compose.yml "
        f"--file {compose_override_argument} up --build"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
